packages:
  - apps/*
  - packages/*
  - services/*

strictPeerDependencies: true

overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.12

allowBuilds:
  esbuild: true
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - bullmq@6.0.7
